FROM ztf-viewer

RUN apt update \
    && apt install -y redis-server

WORKDIR /app
RUN uv sync --locked --group tests --group deploy

COPY tests /tests

ENTRYPOINT ["python", "-m", "pytest", "/tests"]
